### ISSUE TITLE
退出时报错

### ISSUE THREAD

**Issue by HT1657** [JDDKCN/NyanKoLauncher#2]
就是正常按下退出按钮后就报错了
![image](https://github.com/user-attachments/assets/b71c1629-57a4-4ac8-83aa-962ad2558934)
以下是报错详细信息

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\31541\AppData\Local\Temp\KCN\Process7wsGJSbN.bat'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at NyanKoLauncher.Share.Utils.ProcessUtil.RunProcess(String[] line, Boolean createNoWindow)
   at NyanKoLauncher.Share.Service.RunMongoDBService.StopMongoDB()
   at NyanKoLauncher.Desktop.MainFrom.OnClosed(EventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at Sunny.UI.UIForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
NyanKoLauncher.Desktop
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
SunnyUI
    程序集版本:3.8.0.1
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.InteropServices
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Specialized
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Common
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
NyanKoLauncher.Share
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Newtonsoft.Json
    程序集版本:13.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Serialization.Formatters
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Concurrent
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Serialization.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Numerics
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Private.Uri
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq.Expressions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ObjectModel
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Data.Common
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Xml.ReaderWriter
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Private.Xml
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Memory
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Console
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
SunnyUI.Common
    程序集版本:3.8.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.Thread
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.AspNetCore.Components.WebView.WindowsForms
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.AspNetCore.Components.Web
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.AspNetCore.Components
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Web.WebView2.WinForms
    程序集版本:1.0.1370.28
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Web.WebView2.Core
    程序集版本:1.0.1370.28
    Win32 版本:不可用
    代码库:
----------------------------------------
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Resources.Extensions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.AspNetCore.Components.WebView
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.NonGeneric
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.Http
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.Process
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.Sockets
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.Tracing
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.JSInterop
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.Logging
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.Options
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Masa.Blazor
    程序集版本:0.1.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.DependencyInjection
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.Json
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.FileProviders.Composite
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.Tasks
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Numerics.Vectors
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Extensions.FileProviders.Embedded
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Private.Xml.Linq
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Xml.XDocument
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.Encodings.Web
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.ThreadPool
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Emit.Lightweight
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Intrinsics
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
BemIt
    程序集版本:2.2.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
OneOf
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
netstandard
    程序集版本:2.1.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.RegularExpressions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
MongoDB.Bson
    程序集版本:3.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
MongoDB.Driver
    程序集版本:3.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
DnsClient
    程序集版本:1.6.1.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Security.Cryptography
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.Encoding.Extensions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.NameResolution
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.Overlapped
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Security.Cryptography.X509Certificates
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.DiagnosticSource
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.Security
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Loader
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.resources
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Metadata
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Immutable
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------

************** JIT 调试 **************

**Comment by HT1657** [comment]
自己装了jdk和net9就好了（？
